### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by simon-tarr** [sunilale0/django-stripe-subscription#2]
Hi, Thanks for your time in putting this guide together, it looks very comprehensive. I'd like to follow your tutorial and run the example. However, I can't find requirements.txt - are you able to upload this?

Many thanks!

**Comment by elabdesunil** [comment]
Thank you for checking my repo. I just added `requirements.txt` file. Let me know if you run into a problem.

**Comment by simon-tarr** [comment]
Thank you for uploading requirements.txt. I can confirm that I can now load your example fine.
